# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_members', models.IntegerField(default=2)),
                ('iterative_soulmates', models.BooleanField(default=False)),
                ('algorithm_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Account in Progress', max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(default='empty@gmail.com', max_length=60)),
                ('skills', models.CharField(default='No bio has been added yet.', max_length=300)),
                ('owner', models.BooleanField(default=False)),
                ('security_code', models.IntegerField(default=972124)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_ranking', models.CharField(default='', max_length=1000)),
                ('members_ranking', models.CharField(default='', max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(default=models.CharField(max_length=30), max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('qualifications', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('teacher', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('password', models.CharField(default='', max_length=16)),
                ('url', models.CharField(default=models.CharField(max_length=16), max_length=16)),
                ('teams_decided', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.MasterTeam')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Space')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Space'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Space'),
        ),
        migrations.AddField(
            model_name='member',
            name='spaces',
            field=models.ManyToManyField(to='main.Space'),
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(to='main.Team'),
        ),
        migrations.AddField(
            model_name='masterteam',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Space'),
        ),
    ]
