# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180713_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='representative',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
        ),
    ]
